### ISSUE TITLE
rlang compilation failed ?

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/tgR#11]
While loading tgR couple of issues:

**1. While installing the new tGR:** 

Skipping install of 'tgR' from a github remote, the SHA1 (a1f41fb1) has not changed since last install.
  Use `force = TRUE` to force installation

I forced installation but then these issues came up : 

**2. rlang installation error**

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rlang’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rlang’
Error: Failed to install 'tgR' from GitHub:
  (converted from warning) installation of package ‘rlang’ had non-zero exit status
> library(tidyverse); library(aws.s3); library(tgR); library(furrr); library(future); library(checkmate)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.2.0 is already loaded, but >= 0.2.1 is required

**Is this a tGR issue?**

**Comment by vortexing** [comment]
@sitapriyamoorthi did we figure out what the problem was here?  I feel like we did but I'm not sure what the resolution was.

**Comment by sitapriyamoorthi** [comment]
We definitely did resolve this. I believe TgR does not directly update its dependencies. And I had lagged behind on some of the updates. After updating it appears the issue seems to have been resolved.

**Comment by vortexing** [comment]
Gotcha.  and you mean `remotes::install_github()` doesn't install all the dependencies of the dependencies.  ;)  Cool.  I'll close this!

**Comment by sitapriyamoorthi** [comment]
That is the conclusion we came to.
